name = "NME"
author = "Ned"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "336a27ab034122216074991688bf4f83bb85afe8151e8faf34981febdd5c66ca"

[versions]
forge = "36.2.39"
minecraft = "1.16.5"

[options]
acceptable-game-versions = ["1.16.4", "1.16.5"]
