name = "NME"
author = "Ned"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f57298dec7d5e1e23157ed3f6a6153350d229a8ff704d8153026c194dbaf6a51"

[versions]
forge = "36.2.39"
minecraft = "1.16.5"

[options]
acceptable-game-versions = ["1.16.4", "1.16.5"]
