name = "NME"
author = "Ned"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "011b263dfcd3a71904337eb2f253be82f2f4ce9162b11d4c03153b699ff62a3f"

[versions]
forge = "36.2.39"
minecraft = "1.16.5"

[options]
acceptable-game-versions = ["1.16.4", "1.16.5"]
