name = "NME"
author = "Ned"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bae2f03a57cd3a28e3884e121fc9a81ba09d7927b27ee3e4d0b3f5cb42c2bc46"

[versions]
forge = "36.2.39"
minecraft = "1.16.5"

[options]
acceptable-game-versions = ["1.16.4", "1.16.5"]
