name = "NME"
author = "Ned"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "614213f6896a79c388f2c7b19092f280f88f8ed0e732ae43d242431696461cd8"

[versions]
forge = "36.2.39"
minecraft = "1.16.5"

[options]
acceptable-game-versions = ["1.16.4", "1.16.5"]
